group: travis_latest
language: python
cache: pip
python:
- 2.7

install:
- pip install flake8 pytest
- pip install unicode unidecode lxml requests openpyxl

script:
- ./ci/travis.sh

notifications:
  email:
    recipients:
    - tondrej@cz.ibm.com
    #- tomas_macek@cz.ibm.com
    #- tereza.pytelova@cz.ibm.com
    on_success: change
    on_failure: always
